!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 2, y: 0, z: 2}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 10, y: 0, z: 32}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}