!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [45]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 23, y: 0, z: 17}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 17, y: 0, z: 23}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}