!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 1}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
      sizes:
      - !Vector3 {x: 2, y: 1, z: 2}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 35}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoalBounce
      positions:
      - !Vector3 {x: 6.66, y: 0, z: 15}
      - !Vector3 {x: 13.33, y: 0, z: 15}
      - !Vector3 {x: 20, y: 0, z: 15}
      - !Vector3 {x: 26.66, y: 0, z: 15}
      - !Vector3 {x: 33.33, y: 0, z: 15}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}