!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 1}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 3, y: 1, z: 40}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 30, y: 0, z: 30} 
      - !Vector3 {x: 10, y: 0, z: 30}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 2, y: 2, z: 2}