!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 6
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [60]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 4.6, y: 0, z: 10}
      - !Vector3 {x: 4.6, y: 0, z: 30}
      - !Vector3 {x: 4.6, y: 3, z: 20}
      - !Vector3 {x: 5.4, y: 0, z: 10}
      - !Vector3 {x: 5.4, y: 0, z: 30}
      - !Vector3 {x: 5.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 9.6, y: 0, z: 10}
      - !Vector3 {x: 9.6, y: 0, z: 30}
      - !Vector3 {x: 9.6, y:  3, z: 20}
      - !Vector3 {x: 10.4, y: 0, z: 10}
      - !Vector3 {x: 10.4, y: 0, z: 30}
      - !Vector3 {x: 10.4, y: 3,  z: 20}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 14.6, y: 0, z: 10}
      - !Vector3 {x: 14.6, y: 0, z: 30}
      - !Vector3 {x: 14.6, y: 3, z: 20}
      - !Vector3 {x: 15.4, y: 0, z: 10}
      - !Vector3 {x: 15.4, y: 0, z: 30}
      - !Vector3 {x: 15.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 19.6, y: 0, z: 10}
      - !Vector3 {x: 19.6, y: 0, z: 30}
      - !Vector3 {x: 19.6, y: 3, z: 20}
      - !Vector3 {x: 20.4, y: 0, z: 10}
      - !Vector3 {x: 20.4, y: 0, z: 30}
      - !Vector3 {x: 20.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 24.6, y: 0, z: 10}
      - !Vector3 {x: 24.6, y: 0, z: 30}
      - !Vector3 {x: 24.6, y: 3, z: 20}
      - !Vector3 {x: 25.4, y: 0, z: 10}
      - !Vector3 {x: 25.4, y: 0, z: 30}
      - !Vector3 {x: 25.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 29.6, y: 0, z: 10}
      - !Vector3 {x: 29.6, y: 0, z: 30}
      - !Vector3 {x: 29.6, y: 3, z: 20}
      - !Vector3 {x: 30.4, y: 0, z: 10}
      - !Vector3 {x: 30.4, y: 0, z: 30}
      - !Vector3 {x: 30.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 34.6, y: 0, z: 10}
      - !Vector3 {x: 34.6, y: 0, z: 30}
      - !Vector3 {x: 34.6, y: 3, z: 20}
      - !Vector3 {x: 35.4, y: 0, z: 10}
      - !Vector3 {x: 35.4, y: 0, z: 30}
      - !Vector3 {x: 35.4, y: 3, z: 20}
      rotations: [0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      - !Vector3 {x: .3, y: 1, z: .3}
      - !Vector3 {x: .3, y: 3, z: .3}
      - !Vector3 {x: .1, y: .1, z: 21}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 38, y: 0, z: 5}
      sizes:
      - !Vector3 {x: 2, y: 0, z: 2}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 5, y: 3.1, z: 20}
      - !Vector3 {x: 10, y: 3.1, z: 20}
      - !Vector3 {x: 15, y: 3.1, z: 20}
      - !Vector3 {x: 20, y: 3.1, z: 20}
      - !Vector3 {x: 25, y: 3.1, z: 20}
      # - !Vector3 {x: 30, y: 3.1, z: 20}
      # - !Vector3 {x: 35, y: 3.1, z: 20}
      sizes:
      # - !Vector3 {x: 1, y: 1, z: 1}
      # - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 30, y: 3.1, z: 20}
      - !Vector3 {x: 35, y: 3.1, z: 20}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}