!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 22.5}
      rotations: [0]
      sizes: 
      - !Vector3 {x: 40, y: .6, z: 35}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 5, y: 0, z: 2.5}
      rotations: [30]
    - !Item
      name: GoodGoalMulti
      positions: 
      - !Vector3 {x: 7, y: 1, z: 7}
      - !Vector3 {x: 10, y: 1, z: 10}
      - !Vector3 {x: 13, y: 1, z: 13}
      - !Vector3 {x: 16, y: 1, z: 16}
      - !Vector3 {x: 19, y: 1, z: 19}
      - !Vector3 {x: 22, y: 1, z: 22}
      - !Vector3 {x: 25, y: 1, z: 25}
      - !Vector3 {x: 28, y: 1, z: 28}
      - !Vector3 {x: 31, y: 1, z: 31}
      - !Vector3 {x: 34, y: 1, z: 34}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}   
    - !Item
      name: GoodGoal
      positions: 
      - !Vector3 {x: 38, y: 0, z: 2.5}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
