!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: 1.5, y: 5, z: 1}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 21}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]