!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0.5, z: 20}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 35, y: 0, z: 18}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
      rotations: [180]
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 35}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations: [45]