!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [35]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 25}
      - !Vector3 {x: 30, y: 0, z: 30}
      rotations: [0,0]
      colors: 
      - !RGB {r: 0, g: 0, b: 255}
      - !RGB {r: 0, g: 0, b: 255}
      sizes:
      - !Vector3 {x: 5, y: 2, z: 15}
      - !Vector3 {x: 15, y: 2, z: .5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 2, z: 30}      
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
    - !Item
      name: Ramp
      positions: 
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [180]
      sizes:
      - !Vector3 {x: 5, y: 2, z: 5}
      colors:
      - !RGB {r: 255, g: 0, b: 255}