!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: CylinderTunnelTransparent
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [135]
      sizes:
      - !Vector3 {x: 20, y: 3, z: 3}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [45]