!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      - !Vector3 {x: 22, y: 0, z: 24.5}
      - !Vector3 {x: 24, y: 0, z: 19}
      - !Vector3 {x: 21, y: 0, z: 12.5}
      - !Vector3 {x: 17, y: 0, z: 19.5}
      - !Vector3 {x: 19, y: 0, z: 28.75}
      rotations: [0,0,0,0,0,60]
      sizes:
      - !Vector3 {x: 1, y: 3, z: 10}
      - !Vector3 {x: 3, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 12}
      - !Vector3 {x: 7, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 15}
      - !Vector3 {x: 1, y: 3, z: 5}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 23, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 22, y: 0, z: 21}
      rotations: [0]