!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 15, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 15.5}
      - !Vector3 {x: 25, y: 0, z: 20}
      - !Vector3 {x: 20, y: 0, z: 24.5}
      rotations: [0,0,0,0]
      sizes:
      - !Vector3 {x: 1, y: 3, z: 10}
      - !Vector3 {x: 9, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 10}
      - !Vector3 {x: 9, y: 3, z: 1}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 23, y: 0, z: 20}
      rotations: [270]
      sizes:
      - !Vector3 {x: 8, y: 3, z: 2.99}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 16, y: 0, z: 20}