!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [45]
      sizes:
      - !Vector3 {x: 10, y: 0, z: 10}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} 
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 10}
      rotations: [0]