!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0.5
    t: 250
    items:
    - !Item
      name: Wall
      positions: 
      - !Vector3 {x: 20, y: 0, z: 2.5}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 1, z: 5}
      colors:
      - !RGB {r: 0, g: 0, b: 255}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 1, z: 1}
      rotations: [2]
    - !Item
      name: HotZone
      positions:
      - !Vector3 {x: 30, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 20, y: 0, z: 30}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 22.5}
      rotations: [0]
      colors: 
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 1, y: 3, z: 35}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 30, y: 0, z: 35}      
      - !Vector3 {x: 10, y: 0, z: 35}      
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
      - !Vector3 {x: .5, y: .5, z: .5}      
