!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 1}
      rotations: [0]
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 22.5, y: 0, z: 30}
      - !Vector3 {x: 17.5, y: 0, z: 10}
      sizes:
      - !Vector3 {x: 15, y: 0, z: 10}
      - !Vector3 {x: 15, y: 0, z: 10}
      rotations: [0,0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 5, y: 0, z: 20}
      - !Vector3 {x: 35, y: 0, z: 20}
      rotations: [0,0]
      colors: 
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 10, y: 5, z: 30}
      - !Vector3 {x: 10, y: 5, z: 30}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 38}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}  