!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 15}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0, z: 5}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 30, y: 0, z: 10.5}
      rotations: [180]
      sizes:
      - !Vector3 {x: 10, y: 1, z: 5}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 30}
      rotations: [0]
      sizes:
      - !Vector3 {x: 40, y: 0, z: 5}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 12, y: 0, z: 25.5}
      rotations: [180]
      sizes:
      - !Vector3 {x: 10, y: 1, z: 5}
      colors:
      - !RGB {r: 255, g: 0, b: 255}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 38}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 10, y: 0, z: 5}
      rotations: [0]