!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 7.5, y: 0, z: 20}
      - !Vector3 {x: 32.5, y: 0, z: 20}
      rotations: [0,0]
      sizes:
      - !Vector3 {x: 15, y: 0, z: 40}
      - !Vector3 {x: 15, y: 0, z: 40}
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: 30, y: 0, z: 10}
      rotations: [320]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}