!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 37, y: 0, z: 12}
      - !Vector3 {x: 33.5, y: 0, z: 13.5}
      - !Vector3 {x: 35, y: 0, z: 15}
      - !Vector3 {x: 36.5, y: 0, z: 25}
      - !Vector3 {x: 26.5, y: 0, z: 36}
      - !Vector3 {x: 12, y: 0, z: 30}
      rotations: [0,0,0,0,0,0]
      colors: 
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 6, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 4}
      - !Vector3 {x: 2, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 21}
      - !Vector3 {x: 20, y: 3, z: 1}
      - !Vector3 {x: 1, y: 3, z: 20}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 0, z: 13}      
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 1, y: 0, z: 1}
      rotations: [15]