!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 9.5, y: 0, z: 19}
      - !Vector3 {x: 30.5, y: 0, z: 19}
      rotations: [0,0]
      sizes:
      - !Vector3 {x: 19, y: 3, z: 38}
      - !Vector3 {x: 19, y: 3, z: 38}
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 39, y: 0, z: 39}
      - !Vector3 {x: 1, y: 0, z: 39}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}