!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 15}
      - !Vector3 {x: 20, y: 0, z: 25}
      - !Vector3 {x: 20, y: 0, z: 35}
      rotations: [0,0,0]
      sizes:
      - !Vector3 {x: 40, y: 1, z: 10}
      - !Vector3 {x: 40, y: 2, z: 10}
      - !Vector3 {x: 40, y: 3, z: 10}
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 30, y: 0, z: 9}
      - !Vector3 {x: 10, y: 1, z: 19}
      - !Vector3 {x: 20, y: 2, z: 29}
      sizes:
      - !Vector3 {x: 20, y: 1, z: 2}
      - !Vector3 {x: 20, y: 1, z: 2}
      - !Vector3 {x: 20, y: 1, z: 2}
      rotations: [180, 180, 180]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 3, z: 35}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions: 
      - !Vector3 {x: 2, y: 1, z: 2}
      rotations: [45]