!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2
    t: 500
    blackouts: [50, 55, 75, 80, 100, 105, 115, 120, 125, 130, 135]
    items:
    - !Item
      name: GoodGoalMulti
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}