!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2
    t: 250
    items:
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 10, y: 0, z: 30}
      rotations: [0]
      colors: 
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 20, y: 4, z: 1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 10, y: 10, z: 35}    
      - !Vector3 {x: 20, y: 0, z: 25}     
      sizes:
      - !Vector3 {x: 3, y: 3, z: 3}
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 5, y: 0, z: 5}
      rotations: [23]