name: "Label PRs based on changes"

on:
  push:
    branches:
      - main
    paths:
      - 'animal-ai/**'
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/**'
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    paths:
      - 'animal-ai/**'
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/**'
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/labeler@v2
        with:
          configuration-path: .github/labeler.yml