name: 'Manage Stale Content'

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  manage-stale:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 45
          days-before-issue-close: 50
          stale-issue-message: "This issue is stale because it has been open for 45 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 50 days since being marked as stale. Please open a new issue for related bugs."
          days-before-pr-stale: 45 
          days-before-pr-close: 50
          stale-pr-message: "This PR is stale because it has been open for 45 days with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 50 days since being marked as stale. Please open a new related PR if necessary."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
