name: Update README with Latest Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      
    - name: Fetch the latest release
      id: get-latest-release
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.rest.repos.getLatestRelease({
            owner: 'Kinds-of-Intelligence-CFI',
            repo: 'animal-ai',
          });
          return response.data.tag_name;

    - name: Update README.md file
      run: |
        LATEST_RELEASE_TAG=${{ steps.get-latest-release.outputs.result }}
        LATEST_RELEASE_URL="https://github.com/Kinds-of-Intelligence-CFI/animal-ai/releases/tag/$LATEST_RELEASE_TAG"
        MD_FILE_PATH="./README.md"
        # This command looks for the markdown link syntax [latest release](URL) and updates the URL
        sed -i "s|\(latest release).*|\(latest release\)\($LATEST_RELEASE_URL\)|" $MD_FILE_PATH
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add $MD_FILE_PATH
        git commit -m "Update README.md with the latest release link - $LATEST_RELEASE_TAG"
        git push

